"""Derived (non-official) OSCAL-compatible export of the reconciled Canadian
catalogue (spec S11.3) and, optionally, of the Medium profile (spec S8.5).

This is explicitly NOT a claim of an official Cyber Centre OSCAL publication
(S11.3, S22): every group/control carries a `remarks`/props trail back to
that fact, and the true Canadian canonical id is always preserved in a
namespaced prop since it often can't be represented as a native OSCAL id
(e.g. "AC-17(400)" is not a valid bare OSCAL identifier).
"""

from __future__ import annotations

import re
import uuid
from pathlib import Path

import orjson

from itsp_kb.config import DEFAULT_DATA_ROOT
from itsp_kb.models.catalogue import CatalogueRecord
from itsp_kb.models.common import RecordKind
from itsp_kb.provenance import utcnow_iso
from itsp_kb.reconcile import load_catalogue

ITSP_NS = "https://cyber.gc.ca/ns/itsp10033"
NOT_OFFICIAL_REMARKS = (
    "This is a derived, unofficial OSCAL-compatible representation generated by itsp-kb from "
    "the reconciled ITSP.10.033 Canadian catalogue. It is NOT an official publication of the "
    "Canadian Centre for Cyber Security."
)

_ENH_SUFFIX_RE = re.compile(r"^(?P<base>[A-Z]{2}-\d{2,3})\((?P<num>\d{2,3})\)$")


def _synthetic_oscal_id(canonical_id: str) -> str:
    """A valid lowercase OSCAL-style id for a record with no NIST upstream id,
    e.g. 'SA-400' -> 'sa-400', 'AC-17(400)' -> 'ac-17.400'."""
    m = _ENH_SUFFIX_RE.match(canonical_id)
    if m:
        return f"{m.group('base').lower()}.{m.group('num')}"
    return canonical_id.lower()


def _oscal_id_for(record: CatalogueRecord) -> str:
    return record.nist_oscal_id or _synthetic_oscal_id(record.id)


def _record_props(record: CatalogueRecord) -> list[dict]:
    return [
        {"name": "canadian-id", "ns": ITSP_NS, "value": record.id},
        {"name": "requirement-kind", "ns": ITSP_NS, "value": record.requirement_kind.value},
        {"name": "origin", "ns": ITSP_NS, "value": record.origin.value},
        {"name": "reconciliation-status", "ns": ITSP_NS, "value": record.reconciliation_status.value},
        {"name": "is-canadian-specific", "ns": ITSP_NS, "value": str(record.is_canadian_specific).lower()},
        {"name": "is-withdrawn", "ns": ITSP_NS, "value": str(record.is_withdrawn).lower()},
    ]


def _record_parts(record: CatalogueRecord) -> list[dict]:
    parts = [{"name": "statement", "prose": record.statement_text}]
    if record.discussion:
        parts.append({"name": "guidance", "prose": record.discussion})
    if record.gc_discussion:
        parts.append({"name": "gc-discussion", "ns": ITSP_NS, "prose": record.gc_discussion})
    return parts


def _build_control(record: CatalogueRecord, enhancements_by_parent: dict[str, list[CatalogueRecord]]) -> dict:
    control = {
        "id": _oscal_id_for(record),
        "class": "ITSP.10.033",
        "title": record.name,
        "props": _record_props(record),
        "parts": _record_parts(record),
    }
    children = enhancements_by_parent.get(record.id, [])
    if children:
        control["controls"] = [_build_control(c, enhancements_by_parent) for c in children]
    return control


def build_oscal_catalog(*, data_root: Path = DEFAULT_DATA_ROOT) -> dict:
    catalogue = load_catalogue(data_root=data_root)
    bases = [r for r in catalogue if r.record_kind == RecordKind.BASE]
    enhancements = [r for r in catalogue if r.record_kind == RecordKind.ENHANCEMENT]

    enhancements_by_parent: dict[str, list[CatalogueRecord]] = {}
    for e in enhancements:
        enhancements_by_parent.setdefault(e.parent_id or "", []).append(e)

    families: dict[str, list[CatalogueRecord]] = {}
    family_names: dict[str, str] = {}
    for r in bases:
        families.setdefault(r.family_id, []).append(r)
        family_names[r.family_id] = r.family_name

    groups = []
    for family_id in sorted(families):
        groups.append(
            {
                "id": family_id.lower(),
                "class": "family",
                "title": family_names[family_id],
                "controls": [_build_control(r, enhancements_by_parent) for r in families[family_id]],
            }
        )

    return {
        "catalog": {
            "uuid": str(uuid.uuid5(uuid.NAMESPACE_URL, "itsp-kb:oscal-catalog")),
            "metadata": {
                "title": "Derived (unofficial) OSCAL representation of ITSP.10.033",
                "last-modified": utcnow_iso(),
                "version": "2.0",
                "oscal-version": "1.2.2",
                "remarks": NOT_OFFICIAL_REMARKS,
            },
            "groups": groups,
        }
    }


def export_oscal_catalog(*, data_root: Path = DEFAULT_DATA_ROOT) -> Path:
    doc = build_oscal_catalog(data_root=data_root)
    out_dir = data_root / "output" / "oscal"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "ITSP_10_033_catalog.json"
    out_path.write_bytes(orjson.dumps(doc, option=orjson.OPT_INDENT_2))
    return out_path


def build_oscal_medium_profile(*, data_root: Path = DEFAULT_DATA_ROOT) -> dict:
    """Optional OSCAL Profile-shaped export of the Medium profile selections (spec S8.5).

    Canadian assurance-activity/profile semantics that don't map cleanly to OSCAL's
    `include-controls` model are carried as namespaced props rather than coerced.
    """
    catalogue = load_catalogue(data_root=data_root)
    selected = [r for r in catalogue if r.profile_memberships.get("medium")]

    include_controls = [
        {
            "with-id": _oscal_id_for(r),
            "props": [
                {"name": "canadian-id", "ns": ITSP_NS, "value": r.id},
                {"name": "requirement-kind", "ns": ITSP_NS, "value": r.requirement_kind.value},
            ],
        }
        for r in selected
    ]

    return {
        "profile": {
            "uuid": str(uuid.uuid5(uuid.NAMESPACE_URL, "itsp-kb:oscal-medium-profile")),
            "metadata": {
                "title": "Derived (unofficial) OSCAL representation of ITSP.10.033-01 (Medium impact)",
                "last-modified": utcnow_iso(),
                "version": "2.0",
                "oscal-version": "1.2.2",
                "remarks": NOT_OFFICIAL_REMARKS,
            },
            "imports": [{"href": "./ITSP_10_033_catalog.json"}],
            "merge": {"as-is": True},
            "modify": {"set-parameters": []},
            "controls": {"include-controls": include_controls},
        }
    }


def export_oscal_medium_profile(*, data_root: Path = DEFAULT_DATA_ROOT) -> Path:
    doc = build_oscal_medium_profile(data_root=data_root)
    out_dir = data_root / "output" / "oscal"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "ITSP_10_033_01_medium_profile.json"
    out_path.write_bytes(orjson.dumps(doc, option=orjson.OPT_INDENT_2))
    return out_path
